---
name: Create a tag from version.rb

on:
  workflow_dispatch:

jobs:
  gem:
    runs-on: ubuntu-latest
    steps:
      - name: "Get plugin version"
        id: 'gv'
        uses: "stejskalleos/hola_stejzyy23/.github/actions/gem_version@main"
  tag:
    runs-on: ubuntu-latest
    needs: gem
    steps:
      - name: Echo
        run: echo ${{needs.gem.outputs.gem-version}}
      - name: "Create a tag"
        uses: "stejskalleos/hola_stejzyy23/.github/actions/create_tag@main"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{needs.gem.outputs.gem-version}}
