---
name: Create a tag from version.rb

on:
  workflow_dispatch:

jobs:
  meh:
    runs-on: ubuntu-latest
    steps:
      - name: "Get plugin version"
        id: 'gv'
        uses: "stejskalleos/hola_stejzyy23/.github/actions/gem_version@main"
      - name: Echo
        run: echo ${{ steps.gv.outputs.stdout }}
      - name: "Create a tag"
        uses: "stejskalleos/hola_stejzyy23/.github/actions/create_tag@main"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.gv.outputs.stdout }}
