---
name: Create a tag from version.rb

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get plugin version"
        id: 'gv'
        uses: "stejskalleos/hola/.github/actions/gem_version@main"
      - name: "Create a tag"
        uses: "stejskalleos/hola/.github/actions/create_tag@main"
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{needs.gv.outputs.version}}
