name: release

on:
  push:
    paths:
      - "lib/version.rb"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Set variables
        run: |
          VER=$(bundle exec ruby -e 'puts Hola::VERSION')
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.VERSION }}"
  gem:
    name: Release gem
    uses: theforeman/actions/.github/workflows/release-gem.yml@v0
    with:
      allowed_owner: stejskal_leos
      #allowed_owner: theforeman
    secrets:
      api_key: ${{ secrets.RUBYGEM_API_KEY }}
