name: release_two

on:
  push:
    paths:
      - "lib/version.rb"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
#       - uses: GoogleCloudPlatform/release-please-action@v2
#         id: release
#         with:
#           release-type: ruby
#           package-name: release-please-demo
#           bump-minor-pre-major: true
#           version-file: "lib/version.rb"
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - name: Set variables
        run: |
          VER=$(bundle exec ruby -e 'puts Hola::VERSION')
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
